### ISSUE TITLE
Video download interrupted (audio works fine)

### ISSUE THREAD

**Issue by egorvinogradov** [Prividen/kinescope-downloader#2]
Hi,

Thank you for your downloader script!

I can't however get it to work.

- It successfully downloads the audio (I have the `.audio` file downloaded).
- It then proceeds to download the video and successfully downloads _some_ segments (in my case 39 out of 475)
- Then shows the error below

Example: video ID 201403552

Any idea how to fix this? Unfortunately, I'm not very familiar with Python. Thank you!

```
Get video description... Done.

Get audio stream...
Media segment: 446/446 (100.00%) 
Audio stream done.

Get video stream...
Traceback (most recent call last):
  File "/Users/user/Downloads/kinescope-downloader-master/./kinescope-downloader.py", line 174, in <module>
    video += get_segments(
  File "/Users/user/Downloads/kinescope-downloader-master/./kinescope-downloader.py", line 81, in get_segments
    media += get_media_byte_range(req, offs_a, offs_b, seg_from, seg_pointer - 1, total_segments)
  File "/Users/user/Downloads/kinescope-downloader-master/./kinescope-downloader.py", line 39, in get_media_byte_range
    return urllib.request.urlopen(req).read()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 472, in read
    s = self._safe_read(self.length)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 615, in _safe_read
    raise IncompleteRead(data, amt-len(data))
http.client.IncompleteRead: IncompleteRead(16846811 bytes read, 6817519 more expected)
```

**Comment by Prividen** [comment]
Hi, I've managed to successfully downloaded this video.

Probably you faced with some local network problems, or Kineskope CDN issue. Could you please check again later, or check another video ID.
